"""Golden test suite -- verify calculations against 24 real example reports.

Each test case is extracted from actual client reports with known-correct values.
Tests verify our calc engine produces matching results within 1% tolerance.

The golden data file (golden_cases.json) is generated by
tests/golden/extract_golden_data.py from the 25 example Excel files.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

GOLDEN_DATA_PATH = Path(__file__).parent / "golden" / "golden_cases.json"


def load_golden_cases() -> list[dict]:
    """Load golden test cases from JSON."""
    if not GOLDEN_DATA_PATH.exists():
        pytest.skip("Golden data not yet extracted -- run extract_golden_data.py first")
    with open(GOLDEN_DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


def _load_config() -> dict:
    config_path = Path(__file__).parent.parent / "src" / "config" / "rates_config.json"
    with open(config_path, encoding="utf-8") as f:
        return json.load(f)


CONFIG = _load_config()

try:
    GOLDEN_CASES = load_golden_cases()
except Exception:
    GOLDEN_CASES = []


# ============================================================
# Imports of calculation tools
# ============================================================
from tools.calc_hivun import calculate_hivun_33, calculate_hivun_375

# ============================================================
# Helper: tolerance assertion
# ============================================================


def assert_within_tolerance(actual: float, expected: float, tolerance: float = 0.01, label: str = ""):
    """Assert actual is within tolerance of expected.

    For expected == 0, use absolute tolerance of 100 ILS.
    """
    if expected == 0:
        assert abs(actual) < 100, f"{label}: expected ~0 but got {actual}"
    else:
        rel_diff = abs(actual - expected) / abs(expected)
        assert rel_diff < tolerance, (
            f"{label}: expected {expected}, got {actual} (diff={rel_diff:.4%}, tolerance={tolerance:.2%})"
        )


# ============================================================
# 1. Hivun 3.75% tests
# ============================================================


class TestGoldenHivun375:
    """Verify 3.75% capitalization against golden data.

    The golden expected value is the GROSS amount:
        sqm_375 * shovi * 0.0375
    which equals calculate_hivun_375(...).gross_hivun
    """

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("hivun_375_gross") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_hivun_375_gross_within_tolerance(self, case):
        """Hivun 3.75% gross amount matches golden data within 1%."""
        inp = case["inputs"]
        exp = case["expected"]

        sqm_375 = exp.get("sqm_375", 806.25)
        shovi = inp["shovi_per_sqm"]
        priority = inp.get("priority_area")

        result = calculate_hivun_375(
            sqm_equivalent_375=sqm_375,
            shovi_per_sqm=shovi,
            priority_area=priority,
            development_costs=0.0,  # Golden gross is before dev costs
        )

        assert "error" not in result, f"Calculation error: {result.get('error')}"
        assert_within_tolerance(
            result["gross_hivun"],
            exp["hivun_375_gross"],
            label=f"{case['case_name']} hivun 3.75% gross",
        )

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("hivun_375_net") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_hivun_375_net_within_tolerance(self, case):
        """Hivun 3.75% net (after dev costs) matches golden data within 1%.

        The golden files use a fixed development cost deduction of 6562.5
        in the 3.75% track (column G), which is a standard per-nachla value
        independent of the sqm-sheet development costs.
        """
        inp = case["inputs"]
        exp = case["expected"]

        sqm_375 = exp.get("sqm_375", 806.25)
        shovi = inp["shovi_per_sqm"]
        priority = inp.get("priority_area")

        # The golden files use a fixed deduction of 6562.5 for the 3.75% track
        golden_dev_cost = 6562.5

        result = calculate_hivun_375(
            sqm_equivalent_375=sqm_375,
            shovi_per_sqm=shovi,
            priority_area=priority,
            development_costs=golden_dev_cost,
        )

        assert "error" not in result, f"Calculation error: {result.get('error')}"
        assert_within_tolerance(
            result["net_after_dev_costs"],
            exp["hivun_375_net"],
            label=f"{case['case_name']} hivun 3.75% net",
        )


# ============================================================
# 2. Hivun 33% (purchase) tests
# ============================================================


class TestGoldenHivun33:
    """Verify 33% purchase track against golden data.

    The golden expected value is the GROSS amount:
        (sqm_nachla + sqm_potential - prior_permits) * shovi * 0.33
    which equals calculate_hivun_33(...).gross_purchase
    """

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("purchase_33_gross") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_hivun_33_gross_within_tolerance(self, case):
        """Hivun 33% gross purchase amount matches golden data within 1%."""
        inp = case["inputs"]
        exp = case["expected"]

        sqm_nachla = exp.get("sqm_nachla_25dunam", 0)
        sqm_potential = exp.get("sqm_potential", 0) or 0
        shovi = inp["shovi_per_sqm"]
        prior_permits = inp.get("prior_permit_fees_sqm", 0) or 0
        priority = inp.get("priority_area")

        result = calculate_hivun_33(
            sqm_equivalent_nachla=sqm_nachla,
            sqm_potential=sqm_potential,
            shovi_per_sqm=shovi,
            prior_permit_fees_post_2009=prior_permits,
            priority_area=priority,
            development_costs=0.0,  # Golden gross is before dev costs
        )

        assert "error" not in result, f"Calculation error: {result.get('error')}"
        assert_within_tolerance(
            result["gross_purchase"],
            exp["purchase_33_gross"],
            label=f"{case['case_name']} hivun 33% gross",
        )

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("purchase_33_net") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_hivun_33_net_within_tolerance(self, case):
        """Hivun 33% net (after dev costs) matches golden data within 1%.

        The golden files use a fixed development cost deduction of 81510
        in the 33% track (column G). This equals the standard per-nachla
        development cost (247000) multiplied by the 33% rate.
        """
        inp = case["inputs"]
        exp = case["expected"]

        sqm_nachla = exp.get("sqm_nachla_25dunam", 0)
        sqm_potential = exp.get("sqm_potential", 0) or 0
        shovi = inp["shovi_per_sqm"]
        prior_permits = inp.get("prior_permit_fees_sqm", 0) or 0
        priority = inp.get("priority_area")

        # The golden files use a fixed deduction of 81510 for the 33% track
        # (= standard dev costs 247000 * 0.33 rate)
        golden_dev_cost = 81510.0

        result = calculate_hivun_33(
            sqm_equivalent_nachla=sqm_nachla,
            sqm_potential=sqm_potential,
            shovi_per_sqm=shovi,
            prior_permit_fees_post_2009=prior_permits,
            priority_area=priority,
            development_costs=golden_dev_cost,
        )

        assert "error" not in result, f"Calculation error: {result.get('error')}"
        assert_within_tolerance(
            result["net_after_dev_costs"],
            exp["purchase_33_net"],
            label=f"{case['case_name']} hivun 33% net",
        )


# ============================================================
# 3. Unit rate verification tests
# ============================================================


class TestGoldenUnitRates:
    """Verify per-sqm unit rates match golden data.

    The Excel files contain pre-computed per-sqm rates for permit fees
    and usage fees. These are derived from shovi and the regulatory
    coefficients.
    """

    def test_permit_fee_per_sqm_main_is_constant(self):
        """Permit fee per sqm for main area is a fixed RMI rate (1486 ILS).

        The golden files all show permit_fee_per_sqm_main = 1486 regardless
        of shovi. This is a published RMI flat rate, not computed from shovi.
        """
        cases_with_rate = [c for c in GOLDEN_CASES if c.get("expected", {}).get("permit_fee_per_sqm_main") is not None]
        assert len(cases_with_rate) > 0, "No cases with permit_fee_per_sqm_main"

        values = {c["expected"]["permit_fee_per_sqm_main"] for c in cases_with_rate}
        # All golden files should show the same constant rate
        assert len(values) == 1, f"Expected a single constant permit fee rate, got {values}"
        # The constant value is 1486
        assert 1486.0 in values

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("usage_fee_per_sqm_residential") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_usage_fee_per_sqm_residential(self, case):
        """Usage fee per sqm for residential matches golden data.

        Formula: shovi * usage_rate(0.05) * main_coeff(1.0)
        """
        inp = case["inputs"]
        exp = case["expected"]

        shovi = inp["shovi_per_sqm"]
        usage_rate = CONFIG["usage_fee_residential"]["value"]

        expected = shovi * usage_rate
        golden_value = exp["usage_fee_per_sqm_residential"]

        assert_within_tolerance(
            expected,
            golden_value,
            label=f"{case['case_name']} usage fee/sqm residential",
        )


# ============================================================
# 4. Split (pitzul) gross tests
# ============================================================


class TestGoldenSplit:
    """Verify split cost gross calculations against golden data.

    The split in the golden data is divided into:
    - split_discounted_gross: first 245/207.5 sqm at 29.25% rate
    - split_undiscounted_gross: remainder at 33% rate
    """

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("split_total_gross") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_split_total_gross_within_tolerance(self, case):
        """Total split cost (gross) matches golden data within 1%."""
        exp = case["expected"]

        split_total = exp["split_total_gross"]

        # Verify the sum of discounted + undiscounted parts
        discounted = exp.get("split_discounted_gross", 0) or 0
        undiscounted = exp.get("split_undiscounted_gross", 0) or 0
        computed_total = discounted + undiscounted

        if split_total and split_total > 0:
            assert_within_tolerance(
                computed_total,
                split_total,
                label=f"{case['case_name']} split total = discounted + undiscounted",
            )

    @pytest.mark.parametrize(
        "case",
        [
            c
            for c in GOLDEN_CASES
            if c.get("expected", {}).get("split_discounted_gross") is not None
            and c.get("expected", {}).get("sqm_split_discounted") is not None
        ],
        ids=lambda c: c["case_name"],
    )
    def test_split_discounted_formula(self, case):
        """Split discounted portion follows the formula: sqm * 0.2925 * shovi."""
        inp = case["inputs"]
        exp = case["expected"]

        sqm_discounted = exp["sqm_split_discounted"]
        shovi = inp["shovi_per_sqm"]

        # The discounted split rate is 29.25% (from priority area config)
        # For standard (no priority) areas: rate = 0.2925
        expected = sqm_discounted * 0.2925 * shovi
        golden = exp["split_discounted_gross"]

        assert_within_tolerance(
            expected,
            golden,
            label=f"{case['case_name']} split discounted formula",
        )


# ============================================================
# 5. Betterment levy tests
# ============================================================


class TestGoldenBettermentLevy:
    """Verify betterment levy on split calculations."""

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("betterment_levy_split") is not None],
        ids=lambda c: c["case_name"],
    )
    def test_betterment_levy_split_present(self, case):
        """Betterment levy on split is a positive value for all cases with splits."""
        exp = case["expected"]
        levy = exp["betterment_levy_split"]
        assert levy > 0, f"{case['case_name']}: betterment levy should be positive"


# ============================================================
# 6. Per-building hasdarah tests
# ============================================================


class TestGoldenHasdarah:
    """Verify per-building hasdarah calculations where available."""

    @pytest.mark.parametrize(
        "case",
        [c for c in GOLDEN_CASES if c.get("expected", {}).get("hasdarah_buildings")],
        ids=lambda c: c["case_name"],
    )
    def test_hasdarah_summary_totals(self, case):
        """Hasdarah building summary rows have non-negative totals."""
        buildings = case["expected"]["hasdarah_buildings"]
        summary_rows = [b for b in buildings if b.get("type") == "summary"]
        for summary in summary_rows:
            # Summary may have total fees
            for key in ["permit_fees", "total_cost", "usage_fees"]:
                val = summary.get(key)
                if val is not None:
                    assert val >= 0, f"{case['case_name']}: summary {key} should be >= 0, got {val}"


# ============================================================
# 7. Cross-validation: hivun 375 gross = sqm_375 * shovi * rate
# ============================================================


class TestGoldenCrossValidation:
    """Cross-validate extracted values for internal consistency."""

    @pytest.mark.parametrize(
        "case",
        [
            c
            for c in GOLDEN_CASES
            if c.get("expected", {}).get("hivun_375_gross") is not None
            and c.get("expected", {}).get("sqm_375") is not None
        ],
        ids=lambda c: c["case_name"],
    )
    def test_hivun_375_formula_consistent(self, case):
        """Verify: hivun_375_gross == sqm_375 * shovi * 0.0375."""
        inp = case["inputs"]
        exp = case["expected"]

        computed = exp["sqm_375"] * inp["shovi_per_sqm"] * 0.0375
        assert_within_tolerance(
            computed,
            exp["hivun_375_gross"],
            label=f"{case['case_name']} hivun 375 formula cross-check",
        )

    @pytest.mark.parametrize(
        "case",
        [
            c
            for c in GOLDEN_CASES
            if (
                c.get("expected", {}).get("purchase_33_gross") is not None
                or c.get("expected", {}).get("purchase_20_gross") is not None
            )
            and c.get("expected", {}).get("sqm_nachla_25dunam") is not None
        ],
        ids=lambda c: c["case_name"],
    )
    def test_purchase_formula_consistent(self, case):
        """Verify: purchase_gross == total_sqm * shovi * rate.

        The rate is typically 0.33 but may be 0.2 for high-value areas.
        Uses the exact total_sqm from the Excel (column B of the purchase row)
        when available, since some cases compute it differently.
        """
        inp = case["inputs"]
        exp = case["expected"]

        # Use the actual total_sqm from the Excel if available
        if exp.get("purchase_total_sqm") is not None:
            total_sqm = exp["purchase_total_sqm"]
        else:
            sqm_nachla = exp["sqm_nachla_25dunam"]
            sqm_potential = exp.get("sqm_potential", 0) or 0
            prior_permits = inp.get("prior_permit_fees_sqm", 0) or 0
            total_sqm = sqm_nachla + sqm_potential - prior_permits

        # Determine which purchase track is used
        if exp.get("purchase_33_gross") is not None:
            golden_gross = exp["purchase_33_gross"]
            rate = exp.get("purchase_rate", 0.33)
        else:
            golden_gross = exp["purchase_20_gross"]
            rate = exp.get("purchase_rate", 0.2)

        computed = total_sqm * inp["shovi_per_sqm"] * rate

        assert_within_tolerance(
            computed,
            golden_gross,
            label=f"{case['case_name']} purchase formula cross-check (rate={rate})",
        )
